version: '3'
services:
  main:
    build:
      context: .
    environment:
      - PULSE_SERVER=unix:/tmp/pulse/native
      - TZ=Asia/Tokyo
    volumes:
      - ./original_music:/music:ro
      - /run/user/1000/pulse/native:/tmp/pulse/native
